### ISSUE TITLE
Validation on userApplication and country

### ISSUE THREAD

**Issue by alexaor** [alexaor/opsys_1.0#10]
Need to validate whether or not all radiobuttons have been checked and need to add Country in the sql query

**Comment by Lizlet** [comment]
will be getting to COO eventually, and gender. no need to add current country as that will be assumed to be norway. validation will be your job :D

**Comment by Lizlet** [comment]
Just added country adn gender to the databse, radiobutton validation, if I am nost mistaken, is already finished, so, closing this.
