### ISSUE TITLE
Login query for employee and donor

### ISSUE THREAD

**Issue by alexaor** [alexaor/opsys_1.0#11]
Need function query which returns a user relevant for the login.

**Comment by Lizlet** [comment]
Need a parameter fro those, birthID being the most sensible (will design with that in mind for now, but its easily changeable.)

**Comment by Lizlet** [comment]
Login for donor is tested and works, though, naturally, I havent updated the databse yet so some stuff is lacking. we still need COO in DonorUser.vb Hell, ill just add it now.

Loging for employee is a bit weird to test, but I will assume for now that its working as intended and merge.
