### ISSUE TITLE
Ansatt - Hasteinnkalling

### ISSUE THREAD

**Issue by TanTan987** [alexaor/opsys_1.0#110]
Programmet kræsjer når jeg velger en type blod (valgte 0+ i dette tilfellet)
Feilmelding:
An unhandled exception of type 'System.InvalidCastException' occurred in Microsoft.VisualBasic.dll
Additional information: Conversion from string "asd" to type 'Double' is not valid.

**Comment by Lizlet** [comment]
dette vil fikses så snart det faktisk er implemenrt, er ikkje et issue.
