### ISSUE TITLE
Ansatt - Bestill time for blodgiver

### ISSUE THREAD

**Issue by TanTan987** [alexaor/opsys_1.0#111]
Ansatt skal ikke kunne booke time for en blodgiver som allerede har booket time.
Klarte å booke time til meg selv kl 11.00, selv om jeg allerede er satt opp til time kl 12.00.
Må få en feilmelding med "Blodgiveren har allerede booket time den (dato) kl (klokkeslett). Avbestill nevnte time for å bestille ny", eller lignende

**Comment by TanTan987** [comment]
I tillegg må listboxen med tid bli oppdatert når man bestiller eller avbestiller time for blodgiver

**Comment by Lizlet** [comment]
done
