### ISSUE TITLE
Need query which for updating info

### ISSUE THREAD

**Issue by alexaor** [alexaor/opsys_1.0#12]
Need a sub which has a donorUser as a parameter and updates personal information in the database

**Comment by Lizlet** [comment]
Completed temporarily until I get around to updating the database with things like gender and country of origin, etc, which, might I add, is also needed in DonorUser in the first place.

**Comment by Lizlet** [comment]
I have written it, but will set it aside temporarily as I have not tested it while I merge some other stuff. it currently throws a notimplementedexception.

**Comment by Lizlet** [comment]
Hmm, ser ut som denne er ferdig faktisk.
