### ISSUE TITLE
Can we decide on what is needed for login?

### ISSUE THREAD

**Issue by Lizlet** [alexaor/opsys_1.0#20]
My personal opinion is that both donors and employees should use either birth number or email.

My main reason for pointing this out is that CheckPassword function that has been laying around undone for a while now since I want the id parameter to be something else, like email or birth number.

**Comment by TanTan987** [comment]
Fine by me! I think birth number is the best alternative, since it is the one that most rarely changes, of the two. Not sure what Grethe would say about it, but who cares

**Comment by Lizlet** [comment]
Since no one else has any opinions we will go with that, code is finished anyway, still need to change labels and stuff in the forms though.
