### ISSUE TITLE
still need gender, and country of origin support in the application

### ISSUE THREAD

**Issue by Lizlet** [alexaor/opsys_1.0#22]
No point having them stored in the database if no users ever need to enter them, and it is never written anywhere.

For countries, it would be sensible to use a combobox, just get a list of countries and either store them as a resource or just put them right into the combobox collection in the designer, up to you.

combobox for gender as well, we're sticking to binary genders. If someone insist on being difficult we can add "Other" to it later....

as for where to store in during runtime, just shove it in the genericuser class.

**Comment by alexaor** [comment]
Gender will be resolved through birtnNO or while registering, country is at the end of the questionaire but might be moved somewhere else at some point
