### ISSUE TITLE
Egenerklæring synlig kun på tappedatoen?

### ISSUE THREAD

**Issue by TanTan987** [alexaor/opsys_1.0#24]
Lurer på om vi skal sette inn en if-setning eller lignende, som gjør at egenerklæringen til blodgiverne kun er synlig på den dagen de skal tappe?

Pseudokode:
If tappedato = dagens dato Then
btn_egenerklæring = synlig
If not tappedato = dagens dato Then
btn_egenerklæring = usynlig
End If

**Comment by Lizlet** [comment]
Om det er snakk om det biten der du skriver egenerkleringen, ja, om det handler om å kunne se den senere, nei. eg mener I alle fall det er en god ide å la folkd kunne se over hva det har svart tidligere.

**Comment by TanTan987** [comment]
hvorfor er det nødvendig at de skal se de tidligere svarene? nå mener jeg for brukerne.

**Comment by Lizlet** [comment]
det er "nødvendig" men eg ser ingen grunn til at de ikkje skal kunne se det.

**Comment by alexaor** [comment]
Knappen er satt til enabled = false om det ikke er dagens dato
