### ISSUE TITLE
Validering av egenerklæring

### ISSUE THREAD

**Issue by alexaor** [alexaor/opsys_1.0#25]
Controls loopen går ikke gjennom radiobuttons i riktig rekkefølge og et av sprøsmålene blir flagget som ubesvart. Kan løses med å legge knappene i en ny array som loopes i værste tilfellet.

**Comment by alexaor** [comment]
Trenger noen til å endre navnet på alle radiobuttons som tilsvarer NEI til formatet RadioQ1N, RadioQ2N, ... , RadioQ58N.

**Comment by TanTan987** [comment]
gjort

**Comment by alexaor** [comment]
Valideringen fungerer nesten perfekt, er noe bugs med iterasjonen som ikke teller riktig
