### ISSUE TITLE
Booke time

### ISSUE THREAD

**Issue by alexaor** [alexaor/opsys_1.0#26]
trenger sql setning som henter ut alle timer på en bestemt dag. Om en har en array med alle timer som det blir ført tappinger kan den sammenlignes med alle tidspunkter det er booket tapping. Om noe matcher fjernes det fra den ene listen og det som kommer ut av listboxen er resterende timer som er tilgjengelige.

**Comment by alexaor** [comment]
mangler bare sql-setningen nå

**Comment by Lizlet** [comment]
ettersom det trengtes en query for å hente alle bookinger i et annet issue så har eg laget det, du kan kan bruke tabellen fra den,

**Comment by iWindj** [comment]
okei bruke an når an har blitt merga

**Comment by Lizlet** [comment]
done and merged.
