### ISSUE TITLE
validering av removeBlood

### ISSUE THREAD

**Issue by alexaor** [alexaor/opsys_1.0#29]
Trenger sql setning som henter resterende blood av spesifik type og så validering på om bruker prøver å hente ut mer blod enn det som er tilgjengelig i blodbanken.

**Comment by Lizlet** [comment]
om dette er på sida med employees så har vi allerede dette. I inventory så har vi lastet ned antall på alt blod av alle type. så om du henter ut et antall der og sjekker det opp mot hvor mye du trenger går det fint. når ansate "tar ut" blod er det bare å slette det elst mot nyeste
