### ISSUE TITLE
Ansatt kalender må implementeres

### ISSUE THREAD

**Issue by alexaor** [alexaor/opsys_1.0#32]

**Comment by alexaor** [comment]
Implementerte kalenderen men bruker dummy-sql funksjon så trenger setning der som returnerer datetime og navn

**Comment by Lizlet** [comment]
Aight, lager bare en query som henter alle bookinger

btw, det er en ide å bruke den samme querieen for queries today, ettersom du kan f.eks, bruke Linq til å finne dagens bookinger i denne tabellene anyway.

**Comment by Lizlet** [comment]
Done
