### ISSUE TITLE
Sjekk om bruker eksisterer i database nårde prøver å registrere

### ISSUE THREAD

**Issue by alexaor** [alexaor/opsys_1.0#35]

**Comment by Lizlet** [comment]
Det finnes allerede en query som sjekker fødselsnummer og password, ettersom brukeren ikke skal kunne vite om det hvilken av det som er feil anyway så er det nok at den retunrere true/false. er mulig at denne crasher om brukeren ikkje fins, men det kan eg alltids fikse

**Comment by Lizlet** [comment]
fiksa det slik at passwordcheck returnered false om brukeren ikkje fins, istedenfor å crashe
