### ISSUE TITLE
Lørdag/Søndag utilgjengelig i monthcalendar?

### ISSUE THREAD

**Issue by TanTan987** [alexaor/opsys_1.0#45]
Poenget her er om Blodbanken skal være åpen på lørdag og søndag..
Lurer på om noen vet hvordan vi endrer lørdag og søndag til utilgjengelig/utrykkbar i MonthCalendar, og om dette eventuelt er noen god idè? Hvordan ser det ut i databasen dersom vi fjerner to dager i uka?

**Comment by Lizlet** [comment]
databasen vil ikkje ha noen problemer siden den bare lagrer datoer. kan ha stengt for blodgivning på søndager (lørdager kan vi enten ha stengt eller kortere dag) men det må være open for hast og slikt?
