### ISSUE TITLE
Skal ansatt kunne fjerne en bruker?

### ISSUE THREAD

**Issue by TanTan987** [alexaor/opsys_1.0#53]
Dersom en blodgiver ikke vil gi mer blod, skal en ansatt kunne fjerne blodgiver fra systemet? Tidligere info kan bli stående, men slik at blodgiver ikke får innkallelse, og at det ikke går an å velge de til hastetappinger etc?

**Comment by Lizlet** [comment]
Nope, bedre å legge inn noe som sier at de ikkje kan kalles inn lenger. en from for bool i databasen elns,

**Comment by TanTan987** [comment]
Ja, om du ser på hvordan det et satt opp på ansatt nå så kan det funke med en bool el. Go for it!

**Comment by Lizlet** [comment]
made queries for it.

**Comment by TanTan987** [comment]
NEI
