### ISSUE TITLE
Innlogging

### ISSUE THREAD

**Issue by TanTan987** [alexaor/opsys_1.0#55]
Må legge inn databasegreier til brukernavn og passord. Kan kommentere ut denne koden så fort den er laget, så vi slipper å logge oss inn når vi tester koden

**Comment by TanTan987** [comment]
Må også legge inn validering

**Comment by Lizlet** [comment]
har allerede kode for passord sjekking, om passordet stemmer er det bare hente in en bruker og pjåte den in i session. eneste som faktisk mangler der er å legge kode det inn i logg in knappen.

**Comment by Lizlet** [comment]
Done, atm ligger det noe default credentials ved inloggingen slik at det ikkje trengs skrive inn noe, for å fikse det er det bare fjerne load subben.
