### ISSUE TITLE
Ansatt - Lager

### ISSUE THREAD

**Issue by TanTan987** [alexaor/opsys_1.0#59]
Legge inn blod + fjerne blod. Må kobles opp til databasen

**Comment by Lizlet** [comment]
Code fro this was made about two weeks ago, but for some reason ,whoever made the dummy function didnt think to include component in the parameters even though there was a dropdown for it, Guess ill fix it, wont take too long, I hope

**Comment by Lizlet** [comment]
Add blood is done, its added to the database, but its not updated in the tables in the program, might do it later, but might also just decide to redownload it form the database as that would be far easier.

**Comment by Lizlet** [comment]
Ferdig med begge.
