### ISSUE TITLE
Ansatt - lager - statistikk

### ISSUE THREAD

**Issue by TanTan987** [alexaor/opsys_1.0#60]
Hva faen skal vi gjøre med denne?

**Comment by Lizlet** [comment]
Om det var op til meg så fjerner vi den bare, mindre arbeid :D

**Comment by TanTan987** [comment]
Mener at det står i oppgavebeskrivelsen at den skal med?!

**Comment by iWindj** [comment]
Den står under funksjonelle krav i oppgavebeskrivelsen

**Comment by Lizlet** [comment]
Eeeh, lame, hva from for statistikk er det som skal med i det tilfelle? vi har allerede full oversikt over hva vi har på lager, mend mindre de faktisk vil see hele tabellen elns, med oversikt over utløpsdato og slikt?

**Comment by TanTan987** [comment]
har laget nytt issue om hva som skal være med her - alex har sagt han skal ta seg av det
