### ISSUE TITLE
Registrer ny bruker

### ISSUE THREAD

**Issue by TanTan987** [alexaor/opsys_1.0#62]
Legge til nye brukere i database

**Comment by Lizlet** [comment]
Made this like a month ago

**Comment by TanTan987** [comment]
Supert! Men en ting; da jeg prøvde dette forrige uke, for å sjekke at valideringen stemte og hva som skjedde i databasen, så jeg at brukeren ble registrert med bare 4 siffer i fødselsdato..Fikk opp feilmelding i programmet, men den ble allikevel lagt inn i databasen. Ser at den ikke ligger inne i User i MySQL lengre, så mulig du har retta på feilen?

**Comment by Lizlet** [comment]
Vel, det har eg ikkje, eg bare sletta den fra databasen, men kan nok alltids få fiksa det.
