### ISSUE TITLE
User - laboratoriesvar

### ISSUE THREAD

**Issue by TanTan987** [alexaor/opsys_1.0#64]
Lage kode som kobler denne opp mot lab-svarene som ansatt legger inn. Må også lage noe for hvordan det skal se ut her

**Comment by TanTan987** [comment]
Skal de kunne se tidligere lab svar også?

**Comment by alexaor** [comment]
Den bruker nå dummyfunksjon men viser hva labresultatene er brukeren

**Comment by TanTan987** [comment]
Labresultat må overskive tidligere resultat

**Comment by Lizlet** [comment]
Fiksa query for dette itdligere. bruker skal ikkje kunne endre på lavsvar, så de forblir disabla. labsvar funker helt fint på ansatt siden sist eg sjekka.
