### ISSUE TITLE
Registrering av bruker

### ISSUE THREAD

**Issue by TanTan987** [alexaor/opsys_1.0#68]
Må ha en feilmelding dersom bruker allerede finnes. (programmet kræsjer nå om du prøver å registrere lik bruker)

**Comment by Lizlet** [comment]
Query is fine here, rest is on the UI side, I have no intention of trying to decipher whatever it is that is going on there so ill leave that to Alex

**Comment by alexaor** [comment]
Registreringen funker, men funskjonen returnerer -3 selv om email og føds.ID ikke er i databasen

**Comment by Lizlet** [comment]
registrering er ferdig n[
