### ISSUE TITLE
User - Personalia - Endre personalia

### ISSUE THREAD

**Issue by TanTan987** [alexaor/opsys_1.0#70]
Dersom en bruker endrer på personalia - blir de da sendt til databasen med nye endringer?
F.eks hvis de legger til et etternavn - fra Amelia Pond til Amelia Fuckface Pond - Blir Fuckface lagt inn i databasen som ekstra etternavn? Samme spørsmål gjelder hvis en blodgiver f.eks flytter, blir ny adresse sendt til databasen?

**Comment by Lizlet** [comment]
Wrote the code for it ages ago, didn't test it though, just did, it works.
