### ISSUE TITLE
Ansatt - Laboratoriesvar - Hent pasient

### ISSUE THREAD

**Issue by djroggy** [alexaor/opsys_1.0#74]
Finner ikke pasienter ved hjelp av fødselsnummer

**Comment by djroggy** [comment]
Rettelse, noen av blodgiverene funker, andre funker ikke. Vet ikke hvorfor.

**Comment by Lizlet** [comment]
Den funksjonen funket fint, var noen av User-ene i databasen som var ufullsendige og det tulla med programmet etter som det ikkje sjekka for ting som alltid vil være der.
