### ISSUE TITLE
User - Innkallelser - Book time

### ISSUE THREAD

**Issue by TanTan987** [alexaor/opsys_1.0#75]
Blodgiver kan ikke velge en dato som er før 3 mnd etter siste gang han gav blod.
Det vil si at kalenderen skal være blank fram til første dato (3 mnd) etter forrige dato han gav blod.
Hvis blodgiver skal velge dagens dato, kan han heller ikke velge timer som er før det klokka er nå. (hvis klokka f.eks er 12 nå kan han ikke velge å booke time kl 11)
Dager før dagens dato må også være usynlig

**Comment by Lizlet** [comment]
done. keep in mind though, I noticed when I was doing this that some of the users i generated for populate hte database has their previous donation in the future, which is amusing.
