### ISSUE TITLE
Ansatt - Statistikk

### ISSUE THREAD

**Issue by TanTan987** [alexaor/opsys_1.0#92]
- Registreringer (antall blodgivere)
- Tappinger (hvilken dag er mest attraktiv å tappe på)
- Blodtype (hvilken type er mest vanlig)
- Gjennomsnittlig tapping (hvor ofte er det vanlig å tappe)
- Chart av uken
- Menn/Kvinner
- Alder (gjennomsnittsalder)

**Comment by alexaor** [comment]
Har nå statistikk på ukens bookede tappinger og antall kvalifiserte donører i forskjellige blodtyper. Om noe mer statistikk skal legges til kan vi ha en ny issue når de andre tingene er ferdige
