### ISSUE TITLE
User - Dine blodgivninger

### ISSUE THREAD

**Issue by TanTan987** [alexaor/opsys_1.0#96]
Hvis f.eks jeg (brukeren Tania) booker en time, så skal det stå
- antall ganger du har gitt blod (0 hvis du ikke har gitt blod før)
- dato du sist gav blod ("du har ikke gitt blod" hvis du ikke har gitt blod)
- tre måneder etter booket dato under "Dato neste gang du kan gi blod"
- booket dato under "Din neste tapping"
Foreløpig kommer det ikke opp noe her

**Comment by Lizlet** [comment]
nettop fiksa :D
